server:
  port: 8081

#设置feign连接超时和读取超时
feign:
  client:
    config:
      default:
        read-timeout: 3000
        connect-timeout: 3000
      #配置单独client的 超时配置
      sms:
        read-timeout: 2000
      cl:
        read-timeout: 2000
        connect-timeout: 2000
sms:
  ribbon:
    listOfServers: localhost:8080,localhost:8888

#禁止ribbon自动失败重试
ribbon:
  MaxAutoRetriesNextServer: 0

logging:
  level:
    org:
      springframework:
        jpa: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://59.36.170.213:3306/mydb?connectTimeout=5000&characterEncoding=UTF-8&useSSL=false
    platform: mysql
    hikari:
      password: Maxwell0326
      username: root
      maximum-pool-size: 100
      #请求连接超时
      connection-timeout: 10000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false


