server:
  port: 8081

#设置feign连接超时和读取超时
feign:
  client:
    config:
      default:
        read-timeout: 3000
        connect-timeout: 3000
      #配置单独client的 超时配置
      sms:
        read-timeout: 2000
      cl:
        read-timeout: 2000
        connect-timeout: 2000

#指定单个client的负载均衡列表
sms:
  ribbon:
    listOfServers: localhost:8080,localhost:8888

client:
  ribbon:
    listOfServers: localhost:8080,localhost:8081


#禁止ribbon自动失败重试
ribbon:
  MaxAutoRetriesNextServer: 0

#打印事务
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
spring:
  redis:
    host: 59.36.170.213
    port: 6379
    password: Maxwell
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://59.36.170.213:3306/mydb?connectTimeout=5000&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true
    platform: mysql
    hikari:
      password: Maxwell0326
      username: root
      maximum-pool-size: 100
      #请求连接超时
      connection-timeout: 10000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
  jackson:
    serialization:
      write-enums-using-index: true
  #开启jmx
  jmx:
    enabled: true
  rabbitmq:
    host: 59.36.170.213
    port: 5672
    username: Maxwell
    password: GoddessWangJie

#  aop:
#    proxy-target-class: false

user:
  name: Maxwell Mao

#actuator 相关配置
management:
  endpoint:
    health:
      show-details: always
  server:
    port: 45678
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /admin
#  metrics:
#    export:
#      influx:
#        enabled: true
#        uri: http://localhost:8086
#        step: 1S

