---
--- Generated by Luanalysis
--- Created by maxwell.
--- DateTime: 2023/4/11 23:17

local voucherId = ARGV[1]

local userId = ARGV[2]

-- 库存key
local stockKey = 'seckill:stock:' .. voucherId

-- 订单key
local orderKey = 'seckill:order:' .. userId

if (tonumber(redis.call('get', stockKey)) <= 0) then
    --库存不足
    return 1
end






